name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: Construir y ejecutar pruebas
        run: |
          chmod +x gradlew
          ./gradlew --tests runners.RunnerTestE2E